server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/powerup
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

appDescription: "Pragma Powerup"
appVersion: "1.0.0"
debug: true